### ISSUE TITLE
giving a struct to Vutuv.Repo.update/2 is deprecated

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#52]
During login Phoenix prints the following warning message:

```
warning: giving a struct to Vutuv.Repo.update/2 is deprecated. Ecto is unable to properly track changes when a struct is given and an Ecto.Changeset must be given instead
    (ecto) lib/ecto/repo/schema.ex:25: Ecto.Repo.Schema.update!/4
    (vutuv) lib/vutuv/magiclink.ex:8: Vutuv.MagicLink.gen_magic_link/1
    (vutuv) web/controllers/auth.ex:34: Vutuv.Auth.login_by_email/3
    (vutuv) web/controllers/session_controller.ex:9: Vutuv.SessionController.create/2
```

**Comment by cjfreeze** [comment]
Looks like standard practice is to feed your changes through the changeset function. That's my bad, I'll implement it that way from now on. Working on fix now.
