### ISSUE TITLE
Deprecation warning in web/models/slug.ex

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#74]
```
warning: passing :empty to Ecto.Changeset.cast/3 is deprecated, please pass an empty map or :invalid instead
    (vutuv) web/models/slug.ex:21: Vutuv.Slug.changeset/2
    (vutuv) web/controllers/slug_controller.ex:18: Vutuv.SlugController.new/2
    (vutuv) web/controllers/slug_controller.ex:1: Vutuv.SlugController.action/2
    (vutuv) web/controllers/slug_controller.ex:1: Vutuv.SlugController.phoenix_controller_pipeline/2
```

**Comment by cjfreeze** [comment]
That referenced commit 1a1fd80 was a mistake. Please disregard. The correct commit was the earlier one, ea4f845.
